name: Build, Package and Upload a S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Project
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ProyectoConsola.sln /t:Rebuild /p:Configuration=Release

      - name: Package Project
        run: |
          mkdir deploy
          xcopy /Y /I ProyectoConsola\bin\Release\* deploy\
          powershell -Command "Compress-Archive -Path 'deploy\*' -DestinationPath 'Calculator.zip'"

      # Paso de depuración: listar el contenido de la carpeta deploy
      - name: List deploy folder for debugging
        run: dir deploy

      # Paso de depuración: listar el contenido del directorio raíz
      - name: List root folder for debugging
        run: dir

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload Artifact to S3
        run: aws s3 cp Calculator.zip s3://calculadora-bucket-app/Calculator.zip
